# Exported from Render on 2025-12-11T07:59:07Z
version: "1"
projects:
- name: milkbill
  environments:
  - name: Production
    services:
    - type: web
      name: milkbill
      runtime: python
      repo: https://github.com/KIRUBAKARAN83/milkbill
      plan: free
      envVars:
      - key: urlpatterns
        sync: false
      - key: setting
        sync: false
      - key: settings
        sync: false
      region: virginia
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn milkproject.wsgi
      autoDeployTrigger: commit
      rootDir: backend
